"""Hardware-free verification of geometry, excitation, fitting and motion cleanup."""
import json
from pathlib import Path
import tempfile
import unittest
from unittest.mock import Mock, patch

import numpy as np

from gello_teleop.build_gello_urdf import build_model, build_preview, template, write_xml
from gello_teleop.gello_identification import (ExcitationPlan, fit_dataset, fit_observable,
                                              initial_config, save_npz, smooth_derivatives)
from gello_teleop.gello_identification_hardware import IdentificationBus, collect
from gello_teleop.reconstruct_gello_geometry import reconstruct, frame, rpy, HORNS, CASES
from gello_teleop.measure_gello_ranges import measured_config, stable_snapshot
from gello_teleop.verify_gello_directions import review_step, run as verify_directions


def config(n=2):
    result = initial_config({'joint_ids': list(range(1, n+1))})
    result.update({'center_rad': [0]*n, 'lower_rad': [-1]*n, 'upper_rad': [1]*n,
                   'encoder_offsets_rad': [np.pi]*n, 'encoder_signs': [1]*n,
                   'joint_coordinates_verified': True, 'elastic_elements': 'none'})
    return result


def motor(motor_id):
    return {'id': motor_id, 'mode': 3, 'drive_mode': 0, 'homing_offset': 0,
            'torque_on': 0, 'hardware_error': 0, 'watchdog': 0,
            'pwm_limit': 885, 'position_min': 0, 'position_max': 4095,
            'goal_pwm': 200, 'profile_acceleration': 0, 'profile_velocity': 0}


class GeometryTest(unittest.TestCase):
    def test_corrected_case_faces_point_outside_their_printed_brackets(self):
        from gello_teleop.build_gello_urdf import MESH_ROOT
        dtype = np.dtype([('n', '<f4', (3,)), ('v', '<f4', (3, 3)), ('a', '<u2')])
        for index in [3, 4, 6]:
            raw = (MESH_ROOT/f'xarm7/L{index}.STL').read_bytes()
            vertices = np.frombuffer(raw, dtype=dtype, offset=84)['v'].reshape(-1, 3)
            case, _, normal, _, _ = CASES[index]
            # The whole bracket is behind the selected external motor seating
            # face; the motor body grows outwards from that face.
            self.assertLess(float(np.max((vertices-np.asarray(case)) @ np.asarray(normal))), .00005)
        self.assertEqual(HORNS[4][0], [1, 83.75, 0])
        self.assertEqual(HORNS[4][1], [0, -1, 0])

    def test_revised_reference_has_parallel_pitch_axes_and_downward_handle(self):
        import pinocchio as pin
        values = reconstruct()
        rotation = np.eye(3)
        axes = []
        # Check the idealized mechanical axes. The user-selected viewer middle
        # posture is independent of this nominal configuration.
        for joint, angle in zip(values['joints'], [0, 0, 0, 90, 0, 90, 0]):
            rotation = rotation @ pin.rpy.rpyToMatrix(np.asarray(joint['rpy']))
            axes.append(rotation[:, 2].copy())
            rotation = rotation @ pin.rpy.rpyToMatrix(np.array([0., 0., np.deg2rad(angle)]))
        self.assertAlmostEqual(abs(axes[1] @ axes[3]), 1., places=8)
        self.assertAlmostEqual(abs(axes[1] @ axes[5]), 1., places=8)
        self.assertLess(abs(axes[4][2]), 1e-5)
        np.testing.assert_allclose(axes[6], [0, 0, -1], atol=1e-5)

    def test_reconstructed_draft_parses_but_is_refused_for_dynamics(self):
        import pinocchio as pin
        values = reconstruct()
        self.assertFalse(values['geometry_verified'])
        self.assertTrue(values['mesh_units_verified'])
        with self.assertRaisesRegex(ValueError, 'Measure/confirm'):
            build_model(values)
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory)/'draft.urdf'
            write_xml(build_model(values, draft=True), path)
            model = pin.buildModelFromUrdf(str(path))
            visual = pin.buildGeomFromUrdf(model, str(path), pin.GeometryType.VISUAL)
            self.assertEqual(model.nv, 7)
            self.assertEqual(len(visual.geometryObjects), 22)
            self.assertTrue(all(j.get('type') == 'continuous' for j in build_model(values, draft=True).findall('joint')))
            with self.assertRaisesRegex(ValueError, 'Unverified geometry draft'):
                fit_dataset(path, 'no_telemetry', 'no_torque')

    def test_visual_places_each_original_horn_axis_at_its_joint(self):
        import pinocchio as pin
        values = reconstruct()
        for link, (point, normal, _) in zip(values['links'][1:], HORNS):
            v = link['visuals'][0]
            rotation = pin.rpy.rpyToMatrix(np.asarray(v['rpy']))
            np.testing.assert_allclose(rotation @ (np.asarray(point)*.001) + v['xyz'], 0, atol=1e-12)
            normal = np.asarray(normal)/np.linalg.norm(normal)
            np.testing.assert_allclose(rotation @ normal, [0, 0, 1], atol=1e-12)
        # Include gimbal-lock cases generated by joints 5 and 7.
        for j in values['joints']:
            rotation = pin.rpy.rpyToMatrix(np.asarray(j['rpy']))
            np.testing.assert_allclose(pin.rpy.rpyToMatrix(np.asarray(rpy(rotation))), rotation, atol=1e-12)

    def test_unmeasured_geometry_cannot_be_built_as_moving_model(self):
        with self.assertRaisesRegex(ValueError, 'Measure/confirm'):
            build_model(template())

    def test_preview_is_fixed_and_contains_all_nine_meshes(self):
        robot, bounds = build_preview()
        self.assertEqual(len(bounds), 9)
        self.assertTrue(all(j.get('type') == 'fixed' for j in robot.findall('joint')))
        base = next(row for row in bounds if row['mesh'].endswith('base.STL'))
        np.testing.assert_allclose(base['size_raw'], [200, 10, 80], atol=1e-4)

    def test_measured_chain_parses_and_invalid_inertia_is_rejected(self):
        import pinocchio as pin
        values = template()
        values.update(geometry_verified=True, mesh_units_verified=True)
        for link in values['links']:
            link['visuals'][0].update(xyz=[0, 0, 0], rpy=[0, 0, 0])
            link['inertial'] = {'mass_kg': 0.05, 'com_m': [0, 0, 0],
                                'inertia_kg_m2': (np.eye(3)*0.0001).tolist()}
        for i, joint in enumerate(values['joints']):
            joint.update(xyz=[0, 0, 0.05], rpy=[0, 0, 0], axis=[0, i % 2, 1-i % 2],
                         lower=-2, upper=2, effort=0.1, velocity=0.2)
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory)/'synthetic.urdf'
            write_xml(build_model(values, require_inertia=True), path)
            model = pin.buildModelFromUrdf(str(path))
            self.assertEqual(model.nq, 7)
            self.assertEqual(list(model.names[1:]), [f'joint{i}' for i in range(1, 8)])
        values['links'][1]['inertial']['inertia_kg_m2'] = np.diag([1, 1, 3]).tolist()
        with self.assertRaisesRegex(ValueError, 'triangle'):
            build_model(values, require_inertia=True)


class ExcitationTest(unittest.TestCase):
    def test_full_trajectory_obeys_bounds_and_starts_finishes_at_rest(self):
        plan = ExcitationPlan(config(7))
        t = np.linspace(0, plan.duration, 2001)
        q, dq, ddq = plan.evaluate(t)
        np.testing.assert_allclose(q[[0, -1]], np.zeros((2, 7)), atol=1e-12)
        np.testing.assert_allclose(dq[[0, -1]], 0, atol=1e-12)
        np.testing.assert_allclose(ddq[[0, -1]], 0, atol=1e-12)
        self.assertTrue(np.all(np.abs(q) <= plan.amplitude+1e-12))
        self.assertTrue(np.all(np.abs(dq) <= plan.velocity_bound+1e-12))
        self.assertTrue(np.all(np.abs(ddq) <= plan.acceleration_bound+1e-12))
        np.testing.assert_allclose(np.gradient(q, t, axis=0)[2:-2], dq[2:-2], atol=3e-5)

    def test_refuses_unmeasured_limits_boundary_wrap_and_excess_speed(self):
        for changes in [{'lower_rad': None}, {'encoder_offsets_rad': [0, 0]},
                        {'duration_s': 1}, {'max_velocity_rad_s': 0.0001},
                        {'amplitude_rad': [2, 2]}]:
            with self.subTest(changes=changes), self.assertRaises(ValueError):
                ExcitationPlan(dict(config(), **changes))


class ManualRangeTest(unittest.TestCase):
    def test_direction_session_records_model_middle_separately_from_old_encoder_coordinates(self):
        values = config(7)
        geometry = reconstruct()
        raw = np.full(7, np.pi)
        samples = [raw.copy()]
        for i in range(7):
            moved = raw.copy()
            moved[i] += .06
            samples.extend([raw.copy(), moved])
        bus = Mock()
        bus.inspect.return_value = {'motors': [motor(i) for i in range(1, 8)]}
        with tempfile.TemporaryDirectory() as directory:
            output = Path(directory)/'directions.json'
            with patch('gello_teleop.verify_gello_directions.IdentificationBus') as bus_class, \
                    patch('gello_teleop.verify_gello_directions.stable_snapshot', side_effect=samples), \
                    patch('builtins.input', return_value=''), patch('builtins.print') as printed:
                bus_class.return_value.__enter__.return_value = bus
                verify_directions(values, geometry, output)
            report = json.loads(output.read_text())
            expected = [90, 0, -90, 90, 0, 90, -90]
            printed.assert_any_call(expected)
            self.assertEqual(report['model_comparison_reference_q_deg'], expected)
            np.testing.assert_allclose(report['reference_model_q_rad'], np.deg2rad(expected))
            np.testing.assert_allclose(report['reference_q_in_existing_coordinates_rad'], 0)
            self.assertFalse(report['joint_coordinates_verified'])
            bus.write_register.assert_not_called()

    def test_direction_check_reports_sign_disagreement_without_changing_mapping(self):
        signs = np.array([1, 1])
        row = review_step([3., 3.], [3., 2.94], 1, signs)
        self.assertFalse(row['configured_sign_matches'])
        self.assertEqual(row['viewer_positive_encoder_sign'], -1)
        np.testing.assert_array_equal(signs, [1, 1])
        self.assertTrue(review_step([3., 3.], [3.06, 3.], 0, signs)['configured_sign_matches'])

    def test_direction_check_rejects_wrong_motor_multiple_joints_and_wrap(self):
        for after in [[3.06, 3.], [3.05, 3.06], [3., .01], [3., 3.001]]:
            with self.subTest(after=after), self.assertRaises(ValueError):
                review_step([3., 3.], after, 1, [1, 1])

    def test_signed_endpoints_inset_and_preserve_unverified_coordinates(self):
        values = config()
        values['encoder_signs'] = [1, -1]
        result = measured_config(values, [np.pi, np.pi],
                                 [[np.pi-.3, np.pi+.4], [np.pi-.2, np.pi+.5]], .02)
        np.testing.assert_allclose(result['lower_rad'], [-.28, -.48])
        np.testing.assert_allclose(result['upper_rad'], [.38, .18])
        self.assertFalse(result['joint_coordinates_verified'])
        self.assertTrue(np.all(np.asarray(result['amplitude_rad']) <= np.deg2rad(3)))
        self.assertEqual(values['lower_rad'], [-1, -1])

    def test_rejects_wrap_ambiguity_and_center_outside_interval(self):
        for endpoints in [[[0.01, 2*np.pi-.01], [3, 3.2]],
                          [[3.3, 3.5], [3, 3.2]], [[3.13, 3.15], [3, 3.2]]]:
            with self.subTest(endpoints=endpoints), self.assertRaises(ValueError):
                measured_config(config(), [np.pi, np.pi], endpoints, .02)

    def test_passive_snapshot_refuses_active_torque_and_movement(self):
        bus = Mock()
        bus.sample.return_value = {'torque_on': np.array([1, 0]),
                                   'hardware_error': np.array([0, 0]), 'raw_q_rad': np.array([3., 3.])}
        with self.assertRaisesRegex(ValueError, '力矩开启'):
            stable_snapshot(bus, sleep=lambda _: None)
        bus.write_register.assert_not_called()
        bus.sample.side_effect = [dict(torque_on=np.zeros(2), hardware_error=np.zeros(2),
                                       raw_q_rad=np.array([3.+i*.01, 3.])) for i in range(10)]
        with self.assertRaisesRegex(ValueError, '保持静止'):
            stable_snapshot(bus, sleep=lambda _: None)



class FittingTest(unittest.TestCase):
    def test_irregular_timestamps_recover_cubic_derivatives(self):
        t = np.linspace(0, 2, 101) + np.sin(np.arange(101))*0.0001
        q = (0.1+0.03*t+0.02*t**2+0.01*t**3)[:, None]
        i, smoothed, dq, ddq = smooth_derivatives(t, q)
        np.testing.assert_allclose(smoothed[:, 0], q[i, 0], atol=1e-11)
        np.testing.assert_allclose(dq[:, 0], 0.03+0.04*t[i]+0.03*t[i]**2, atol=1e-11)
        np.testing.assert_allclose(ddq[:, 0], 0.04+0.06*t[i], atol=1e-10)
        t[50] += 0.5
        with self.assertRaisesRegex(ValueError, 'increase'):
            smooth_derivatives(t, q)

    def test_rank_deficiency_is_reported_with_held_out_prediction(self):
        t = np.linspace(0, 8, 200)
        design = np.stack([np.sin(t), np.cos(0.7*t), 2*np.sin(t)], axis=-1)[:, None, :]
        torque = np.einsum('nij,j->ni', design, [0.1, 0.2, 0.3])
        report, fitted = fit_observable(design, torque, 140)
        self.assertEqual(report['rank'], 2)
        self.assertEqual(report['nullity'], 1)
        self.assertFalse(report['individual_link_parameters_confirmed'])
        self.assertLess(max(report['validation_rmse_nm']), 1e-10)
        self.assertEqual(fitted['observable_basis_scaled'].shape, (3, 2))

    def test_real_regressor_pipeline_predicts_separate_synthetic_torque_samples(self):
        import pinocchio as pin
        urdf = '''<robot name="gello_test"><link name="base"/><link name="link1">
        <inertial><origin xyz="0.2 0 0"/><mass value="0.1"/>
        <inertia ixx="0.001" iyy="0.002" izz="0.002" ixy="0" ixz="0" iyz="0"/></inertial>
        </link><joint name="joint1" type="revolute"><parent link="base"/><child link="link1"/>
        <axis xyz="0 1 0"/><limit lower="-2" upper="2" effort="1" velocity="3"/></joint></robot>'''
        t = np.linspace(0, 20, 801)
        q = (0.4*np.sin(0.8*t)+0.1*np.sin(2.1*t))[:, None]
        dq = (0.32*np.cos(0.8*t)+0.21*np.cos(2.1*t))[:, None]
        ddq = (-0.256*np.sin(0.8*t)-0.441*np.sin(2.1*t))[:, None]
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            model_path, data_path, torque_path = [root/name for name in ['synthetic.urdf', 'data.npz', 'torque.npz']]
            model_path.write_text(urdf)
            model = pin.buildModelFromUrdf(str(model_path))
            data = model.createData()
            tau = np.asarray([pin.rnea(model, data, qi, vi, ai).copy()
                              for qi, vi, ai in zip(q, dq, ddq)])
            tau += 0.015*dq+0.008*np.tanh(dq/0.02)+0.002*ddq
            save_npz(data_path, time_s=t, q_rad=q, metadata_json=json.dumps({
                'session_status': 'complete', 'joint_coordinates_verified': True,
                'joint_names': ['joint1'], 'elastic_elements': 'none', 'synthetic': True}))
            torque_meta = {'calibrated_output_torque': True, 'source': 'SYNTHETIC Pinocchio RNEA test',
                           'joint_names': ['joint1']}
            save_npz(torque_path, time_s=t, tau_nm=tau, metadata_json=json.dumps(torque_meta))
            report, _ = fit_dataset(model_path, data_path, torque_path)
            self.assertLess(max(report['validation_rmse_nm']), 0.001)
            bad = root/'supply_current.npz'
            torque_meta['calibrated_output_torque'] = False
            save_npz(bad, time_s=t, tau_nm=tau, metadata_json=json.dumps(torque_meta))
            with self.assertRaisesRegex(ValueError, 'calibrated'):
                fit_dataset(model_path, data_path, bad)


class HardwareBoundaryTest(unittest.TestCase):
    def bus(self):
        bus = IdentificationBus.__new__(IdentificationBus)
        bus.config = config()
        bus.ids = [1, 2]
        bus.active = False
        bus.original = None
        bus.port = Mock()
        bus.write_register = Mock()
        bus.command = Mock()
        bus.inspect = Mock(return_value={'motors': [motor(1), motor(2)]})
        bus.sample = Mock(return_value={
            'raw_q_rad': np.array([np.pi, np.pi]), 'raw_dq_rad_s': np.zeros(2),
            'current_a': np.zeros(2), 'temperature_c': np.array([24, 24]),
            'voltage_v': np.array([5, 5]), 'hardware_error': np.zeros(2, dtype=int),
            'torque_on': np.zeros(2, dtype=int)})
        return bus

    def test_read_only_close_never_writes_torque_or_goals(self):
        bus = self.bus()
        self.assertEqual(bus.close(), [])
        bus.write_register.assert_not_called()
        bus.port.closePort.assert_called_once()

    def test_all_motors_validate_before_any_write(self):
        for changes in [{'mode': 0}, {'drive_mode': 8}, {'homing_offset': 128},
                        {'torque_on': 1}, {'hardware_error': 1}, {'watchdog': -1}]:
            with self.subTest(changes=changes):
                bus = self.bus()
                bus.inspect.return_value['motors'][1].update(changes)
                sample = {'raw_q_rad': np.array([np.pi, np.pi]), 'raw_dq_rad_s': np.zeros(2)}
                with self.assertRaises(ValueError):
                    bus.arm(ExcitationPlan(bus.config), sample)
                bus.write_register.assert_not_called()
                self.assertFalse(bus.active)

    def test_failed_torque_enable_is_cleaned_up_and_profiles_restored(self):
        bus = self.bus()
        def fail(motor_id, address, size, value):
            if motor_id == 2 and address == 64 and value == 1:
                raise RuntimeError('lost status response')
        bus.write_register.side_effect = fail
        sample = {'raw_q_rad': np.array([np.pi, np.pi]), 'raw_dq_rad_s': np.zeros(2)}
        with self.assertRaisesRegex(RuntimeError, 'lost status'):
            bus.arm(ExcitationPlan(bus.config), sample)
        self.assertTrue(bus.active)
        self.assertEqual(bus.close(), [])
        for motor_id in [1, 2]:
            bus.write_register.assert_any_call(motor_id, 64, 1, 0)
            bus.write_register.assert_any_call(motor_id, 108, 4, 0)
            bus.write_register.assert_any_call(motor_id, 112, 4, 0)
            bus.write_register.assert_any_call(motor_id, 100, 2, 200)

    def test_pose_change_during_arming_never_enables_torque(self):
        bus = self.bus()
        original_sample = dict(bus.sample.return_value)
        bus.sample.return_value = dict(original_sample, raw_q_rad=np.array([np.pi+0.05, np.pi]))
        with self.assertRaisesRegex(ValueError, 'changed during arming'):
            bus.arm(ExcitationPlan(bus.config), original_sample)
        self.assertFalse(any(call.args[1] == 64 and call.args[-1] == 1
                             for call in bus.write_register.call_args_list))
        bus.command.assert_not_called()
        self.assertEqual(bus.close(), [])

    def test_failed_collection_closes_bus_and_marks_partial_log_aborted(self):
        class FakeBus:
            def __init__(self, config):
                self.calls = 0
                self.closed = False
            def __enter__(self):
                return self
            def __exit__(self, *_):
                self.closed = True
            def inspect(self):
                return {'motors': [motor(1), motor(2)]}
            def sample(self):
                import time
                self.calls += 1
                if self.calls == 3:
                    raise TimeoutError('telemetry disconnected')
                stamp = time.monotonic_ns()
                return {'raw_q_rad': np.array([np.pi, np.pi]), 'raw_dq_rad_s': np.zeros(2),
                        'current_a': np.zeros(2), 'temperature_c': np.array([24, 24]),
                        'voltage_v': np.array([5, 5]), 'hardware_error': np.zeros(2, dtype=int),
                        'torque_on': np.zeros(2, dtype=int), 'receive_ns': np.array([stamp, stamp]),
                        'read_started_ns': stamp, 'read_finished_ns': stamp+1}
        bus = FakeBus(config())
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory)/'partial.npz'
            with patch('gello_teleop.gello_identification_hardware.IdentificationBus', return_value=bus):
                with self.assertRaisesRegex(TimeoutError, 'disconnected'):
                    collect(config(), path, duration=10)
            self.assertTrue(bus.closed)
            with np.load(path, allow_pickle=False) as data:
                metadata = json.loads(str(data['metadata_json']))
                self.assertEqual(metadata['session_status'], 'aborted')
                self.assertIn('disconnected', metadata['failure'])
                self.assertEqual(len(data['q_rad']), 1)


if __name__ == '__main__':
    unittest.main()
